# Generated by Django 5.2.6 on 2026-06-16 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Search', '0002_searchhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchhistory',
            name='query',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='searched_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
