# Generated by Django 5.2.6 on 2026-06-16 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Search', '0003_alter_searchhistory_query_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
